### ISSUE TITLE
部分翻译及拼写问题勘误

### ISSUE THREAD

**Issue by hzqd** [rustcollege/glossary#1]
# E
- **enum variant** 目前的翻译是“**枚举成员**”，但”**成员**“对应的英文是”***member***“，且”**成员**“有”**积类型**“(product type)的语义。
**建议：翻译为”枚举变体“更合适。** "**变体**"有”**和类型**“(sum type)的语义

# H
- **handle error** 目前把第一个单词翻译成”**句柄**“存在争议。**handle** 有 ”**处理**“、”**应对**“之意，是否可以考虑选择一个更合适的名字？
- **higher tank type** 这恐怕不止有拼写错误...... ”**高阶类型**“的英文是”**higher-kinded types**“

# I
- **ICE** 备注的 **compiler** 拼写错误（多敲了一个 p

**Comment by sunface** [comment]
好的，感谢建议，我先修改下typo，剩下的等我查询更多资料后，再回复:)

**Comment by sunface** [comment]
词汇对照表已经合并到书籍的主仓库中，如有需要，在那边开issue讨论，过几天后，目前的这个仓库会进行删除，望悉知:)
